name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Build Gradle
        run: flutter build apk --debug

      - run: ls build/app/outputs/flutter-apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: dev
          file: build/app/outputs/flutter-apk/app-debug.apk

      - name: Make version bump script executable
        run: chmod +x version_bump.sh

      - name: Bump version
        run: bash ./version_bump.sh

      - name: Commit new version
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pubspec.yaml
          git diff --quiet || git commit -m "Bump version to $(grep 'version:' pubspec.yaml | cut -d' ' -f2 | tr -d '\n')"
          git push
